llm:
  model_name: Qwen3.5-9B
  api_key: not-needed
  api_url: http://0.0.0.0:8001/v1
  temperature: 0.6
  max_tokens: 32768
  max_workers: 64
  enable_thinking: true
  system_prompt: ""

judge:
  model_name: Qwen3.5-9B
  api_key: not-needed
  api_url: http://0.0.0.0:8001/v1
  temperature: 0.0
  max_tokens: 4096
  system_prompt: ""
  enable_thinking: true
  # 是否使用 LLM judge（如果为 True，会加载 judge_client 并用于评估）
  use_llm_judge: false

repeats: 3 # 使用API调用模型时为1，本地部署为3
max_samples: 0 # 全量为0
datasets_path: datasets
results_path: results
